# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ed6aff7f3a63fece33c9d841e8c22f7ae3225c9640b06714eac43351ddad4ded588b93549e763679a4eafc1f2bfd163b3a0570f916554333caff1d140f1f4f

test:
  secret_key_base: 72a69d11a8b3ec92e036da2ff5b2b7424a9083a5c7ab075905a95c4dbd58b3171f297eab9887f43992a05af8c8603cd548dd7a35c2765bf613ee0af6a337a854

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
